### ISSUE TITLE
Note 96 (and maybe 97) in Harm1

### ISSUE THREAD

**Issue by Blackened15** [trojannemo/Nautilus#1]
Harm1 Note 96 (playable percussion) and 97 (non-playable percussion) are removed by the midi fixer.

While the RBN/C3 documentation do say that percussion should only be on TRACK VOCAL, in practice, it doesn't work that way.  If note 96 (and i'm just assuming the same for 97, as I haven't checked/encountered those atm) is removed from the HARM1 track as per a midi fix, then there just isn't any percussion showing in games (Checked on RB4 and the web preview builder in Onyx).

I just fixed it on my personal build by adding 96 and 97 in the  allowed list in HARM1.

**Comment by trojannemo** [comment]
Thanks for bringing this to my attention. It has been fixed on my end so it will be pushed on v5.1.1 soon. I'm closing this issue as resolved. Any other issues please let me know.
