### ISSUE TITLE
Export Song List causing Unhandled Exception for PDFLibNet.dll or one of its dependencies

### ISSUE THREAD

**Issue by AMurderOfCrows** [trojannemo/Nautilus#2]
This is happening whenever i attempt to export the song list. I'm in Rock Band 3 mode.

![Screenshot 2024-05-11 155111](https://github.com/trojannemo/Nautilus/assets/56582613/566fa355-b45e-4a36-ba4c-7af616373b8e)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'PDFLibNet.dll' or one of its dependencies. The specified module could not be found.
File name: 'PDFLibNet.dll'
   at Nautilus.SetlistExporter.DisplayThumbnail()
   at Nautilus.SetlistExporter.backgroundWorker1_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Nautilus
    Assembly Version: 5.1.2.0
    Win32 Version: 5.1.2.0
    CodeBase: file:///D:/Nautilus/Nautilus.exe
----------------------------------------
Bass.Net
    Assembly Version: 2.4.17.2
    Win32 Version: 2.4.17.2
    CodeBase: file:///D:/Nautilus/bin/Bass.Net.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9236.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
DevComponents.DotNetBar2
    Assembly Version: 7.6.0.0
    Win32 Version: 7.6.0.0
    CodeBase: file:///D:/Nautilus/bin/DevComponents.DotNetBar2.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
PdfFileWriter
    Assembly Version: 1.1.16.2
    Win32 Version: 1.1.16.2
    CodeBase: file:///D:/Nautilus/bin/PdfFileWriter.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by trojannemo** [comment]
Is the library in the /bin folder of the application? If it's compiled, it should be in the folder where the .exe is i.e.
folder -> nautilus.exe and bin\
folder -> bin\ -> dll file

If you're experiencing this from within Visual Studio make sure you've added the library as a reference to your project.

Lastly, do you have .Net Framework 4.8.1 installed?

This tool has been a feature of C3 Tools/Nautilus for nearly a decade. So if it's not working for you it's probably something on your end that we have to troubleshoot.

**Comment by AMurderOfCrows** [comment]
I didn't see anywhere that indicated what version of.net was required. I
pulled down the latest compiled setup from the GitHub. I'll get home in a
little bit and try what you said.

**Comment by trojannemo** [comment]
From the main page of the repository, also known as the README.md file:

"Nautilus is written in C# using .NET Framework 4.8.1 and using Visual Studio 2022 Community Edition. For best results make sure you use the same."

Although I don't think that's your issue.

**Comment by AMurderOfCrows** [comment]
i don't understand the need for me to install visual studio. i don't plan
on developing on this, i just want to print out some setlist booklets based
on my song cache.

As for the readme, i normally look to that for updates and gotchas, not for
critical compatibility requirements. but that's me. In other projects i see
baseline requirements as being part of the initial installer wizard (a pop
up checking for requirements and then promoting or installing them if they
are missing), or i see the requirements on the github page where you
download the latest compiled package.

in any case, .net 4.8.1 didn't help so i'm going to try visual studio as
well. i'm pretty desperate and quickly running out of time, so i'll also
try this on another computer


"So it is written....so it shall come to pass.  Quoth the
Raven....'Nevermore!'"

'Catapultam habeo. Nisi pecuniam omnem mihi dabis, ad caput tuum saxum
immane mittam'

_____________
O Hadoken!
|=( -O)
/\

**Comment by AMurderOfCrows** [comment]
Okay, i tried it on my desktop and this worked with just .Net 4.8.1 and no need for visual studio, so there is definitely something wrong with my laptop. This will get me through this week. Grateful for the software and the assist.
