### ISSUE TITLE
Requests and a bug in Save Scores Viewer

### ISSUE THREAD

**Issue by SonicSBL** [trojannemo/Nautilus#5]
There's currently no option to sort the song list in Save Scores Viewer. It's really hard to find a specific song from the list when they're in an order that makes no sense. Would that be a possibility?

Also, there's a bug where if you manually reset the scores to zero for certain instruments, it reverts the star rating and note percentage after clicking off the song.

For example, here are my keys scores for "Thunder":
![savescores1](https://github.com/user-attachments/assets/89e1de61-cc6c-4c5f-8f11-62e69603837d)

This is what it should look like after resetting the scores for the song:
![savescores2](https://github.com/user-attachments/assets/1536ed9b-e071-41f7-ac89-3b10b8aac12e)

But this is what I get after selecting a new song and coming back:
![savescores3](https://github.com/user-attachments/assets/f853c248-030a-4953-bd34-aad2d1355cc6)

I mentioned this once in the MiloHax Discord once, but it was never done, and with the recent removals of some pro upgrades in RB3 Deluxe, it bears repeating. It would also be nice to have a "Reset Scores" button with the choice of a single instrument or all of them.

**Comment by trojannemo** [comment]
Saves Scores Viewer is created and maintained by StackOverflow, as the app says. I do not have the source code and cannot make changes to it. You need to find him on Discord and ask him to make these changes.

**Comment by trojannemo** [comment]
Please note that with tonight's release there's a new version of this app included with Nautilus. Try it and see if your issue was resolved.
