### ISSUE TITLE
File Analyzer multiple songs counting bug

### ISSUE THREAD

**Issue by EafAtta** [trojannemo/Nautilus#6]
When viewing multiple songs in the File Analyzer, instead of counting each song individually, it adds to each subsequent song

Example, if a song has one solo, every subsequent song will have one solo added, until the next song with a solo, then the next songs will have TWO extra solos, and so on. It makes it unreliable for looking at multiple songs, unless you do each song individually.

**Comment by trojannemo** [comment]
Just saw this. Will work on it for next release.

**Comment by trojannemo** [comment]
Fixed. Will be in v5.2.2. Thanks for bringing it to my attention.
